/* =============================================================================
   RevHops — copy export

   Run:  node tools/copy-export.js

   Writes two files:
     revhops-homepage-copy.txt   for James, to paste into a Google Doc
     tools/copy-map.json         for copy-import.js, not for humans

   Why a map file. Matching edited copy back to the source by searching for the
   old text does not work: "Read more" appears five times, so does
   "[Client name]", and the case study line is repeated in all five hero
   stages. Every string therefore gets an id, and the map records exactly where
   it came from — an index into a deterministic DOM walk, or the nth occurrence
   of a literal in the JS. The importer re-derives both and refuses to write if
   anything has moved.

   The homepage copy lives in TWO files. Most is in index.html, but the whole
   hero — the five stages, their bullets, the card titles — is generated by
   maturity-slider.js from constants. An export that only read the HTML would
   silently miss about half the words on the page.
   ============================================================================= */
'use strict';

const fs = require('fs');
const path = require('path');
const { JSDOM } = require('jsdom');

const ROOT = path.resolve(__dirname, '..');
const OUT_TXT = path.join(ROOT, 'revhops-homepage-copy.txt');
const OUT_MAP = path.join(__dirname, 'copy-map.json');

/* ---------------------------------------------------------------- the HTML */

/* Inline tags are part of a string, not a string of their own. `a` is
   deliberately NOT here: each nav link and footer link is its own line to
   edit, and treating anchors as inline would collapse the whole nav into one. */
const INLINE = new Set(['SPAN', 'B', 'I', 'EM', 'STRONG', 'BR', 'SUP', 'SUB', 'CODE', 'ABBR']);
/* Not copy: decoration, controls, and anything with no words in it. */
const SKIP = new Set(['SCRIPT', 'STYLE', 'SVG', 'IMG', 'BUTTON', 'NOSCRIPT', 'PATH']);

function collectHtmlSlots(doc) {
  const slots = [];
  (function walk(el) {
    for (const child of el.children) {
      if (SKIP.has(child.tagName)) continue;
      const kids = [...child.children].filter(c => !SKIP.has(c.tagName));
      const allInline = kids.every(c => INLINE.has(c.tagName));
      const text = child.textContent.replace(/\s+/g, ' ').trim();
      if (text && allInline) {
        slots.push({
          tag: child.tagName.toLowerCase(),
          cls: child.className || '',
          html: child.innerHTML.replace(/\s+/g, ' ').trim(),
          text
        });
      } else {
        walk(child);
      }
    }
  })(doc.body);
  return slots;
}

/* A readable name for the block a string sits in, so the doc has signposts. */
function sectionLabel(doc, i, slots) {
  return slots[i].section;
}

function labelSections(doc, slots) {
  /* re-walk to tag each slot with the section it belongs to */
  const named = [
    ['header.nav', 'NAV'],
    ['.hero-pin', 'HERO (generated by the slider, see the second half of this file)'],
    ['.logo-band', 'CLIENT LOGO BAND'],
    ['section:has(.svc-list)', 'SERVICES'],
    ['section:has(.case-rail)', 'CASE STUDIES'],
    ['section:has(.about-stack)', 'ABOUT'],
    ['section:has(.tool-clump)', 'TOOL STACK'],
    ['section:has(.testi)', 'TESTIMONIALS'],
    ['section:has(.start-wide)', 'NEXT STEPS'],
    ['footer.footer', 'FOOTER'],
  ];
  const regions = named
    .map(([sel, name]) => { try { return [doc.querySelector(sel), name]; } catch { return [null, name]; } })
    .filter(([el]) => el);

  const all = collectHtmlSlots(doc);
  /* map each collected slot back to its region by walking each region alone */
  const out = [];
  for (const [el, name] of regions) {
    const sub = new JSDOM('<body></body>').window.document;
    void sub;
    const inRegion = [];
    (function walk(node) {
      for (const child of node.children) {
        if (SKIP.has(child.tagName)) continue;
        const kids = [...child.children].filter(c => !SKIP.has(c.tagName));
        const allInline = kids.every(c => INLINE.has(c.tagName));
        const text = child.textContent.replace(/\s+/g, ' ').trim();
        if (text && allInline) inRegion.push(child);
        else walk(child);
      }
    })(el);
    for (const node of inRegion) {
      out.push({
        section: name,
        tag: node.tagName.toLowerCase(),
        html: node.innerHTML.replace(/\s+/g, ' ').trim(),
        text: node.textContent.replace(/\s+/g, ' ').trim()
      });
    }
  }
  void all;
  return out;
}

/* ------------------------------------------------------------------ the JS */

/* Every editable string in maturity-slider.js, in the order it appears, with
   the occurrence index of its literal. Duplicates are the norm here: the case
   study line is identical in all five stages. */
function collectJsSlots(js) {
  const slots = [];
  const counts = Object.create(null);
  const push = (group, label, value) => {
    counts[value] = (counts[value] || 0) + 1;
    slots.push({ group, label, value, nth: counts[value] });
  };

  const stagesSrc = js.slice(js.indexOf('var STAGES = ['), js.indexOf('\n  ];', js.indexOf('var STAGES = [')));
  const blocks = stagesSrc.split(/\n    \{\n/).slice(1);
  blocks.forEach(b => {
    const name = /name: '([^']*)'/.exec(b)[1];
    const list = key => {
      const m = new RegExp(key + ": \\[([\\s\\S]*?)\\]").exec(b);
      return m ? [...m[1].matchAll(/'((?:[^'\\]|\\.)*)'/g)].map(x => x[1]) : [];
    };
    push('HERO STAGE: ' + name, 'Stage name', name);
    list('situation').forEach(v => push('HERO STAGE: ' + name, 'Situation', v));
    list('have').forEach(v => push('HERO STAGE: ' + name, 'Tools they have', v));
    list('missing').forEach(v => push('HERO STAGE: ' + name, 'Tools they are missing', v));
    list('problems').forEach(v => push('HERO STAGE: ' + name, 'Problem', v));
    const who = /who: '([^']*)'/.exec(b);
    const line = /line: '((?:[^'\\]|\\.)*)'/.exec(b);
    if (who) push('HERO STAGE: ' + name, 'Case study client', who[1]);
    if (line) push('HERO STAGE: ' + name, 'Case study line', line[1]);
  });

  push('HERO HEADLINE', 'First half', /var HEAD_LEAD\s*= '([^']*)'/.exec(js)[1]);
  push('HERO HEADLINE', 'Second half', /var HEAD_TAIL\s*= '([^']*)'/.exec(js)[1]);

  const titles = /var CARD_TITLES = \[([\s\S]*?)\]/.exec(js)[1];
  [...titles.matchAll(/'((?:[^'\\]|\\.)*)'/g)].forEach(m => push('HERO CARD TITLES', 'Card title', m[1]));

  const split = /var PROBLEM_SPLIT = \{([\s\S]*?)\n  \};/.exec(js)[1];
  push('HERO PROBLEMS CARD', 'Sub-heading', /head: '([^']*)'/.exec(split)[1]);
  push('HERO PROBLEMS CARD', 'Body',
       [...split.matchAll(/'((?:[^'\\]|\\.)*)'/g)].slice(1).map(m => m[1]).join(''));

  return slots;
}

/* ---------------------------------------------------------------- assemble */

const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const js = fs.readFileSync(path.join(ROOT, 'assets/js/maturity-slider.js'), 'utf8');
const doc = new JSDOM(html).window.document;

const htmlSlots = labelSections(doc, null);
const jsSlots = collectJsSlots(js);
const stamp = (/site\.css\?v=(\d+)/.exec(html) || [, 'unknown'])[1];

const lines = [];
const map = { stamp, html: [], js: [] };

lines.push('REVHOPS HOMEPAGE COPY');
lines.push('Build ' + stamp + '  ·  exported ' + new Date().toISOString().slice(0, 10));
lines.push('');
lines.push('HOW TO USE THIS');
lines.push('  1. Edit only the text that follows each [[id]] label.');
lines.push('  2. Do not change, reorder or delete the [[id]] labels. They are how');
lines.push('     the words get put back into the site.');
lines.push('  3. Keep each entry on ONE line. Let it wrap; do not press Return inside it.');
lines.push('  4. Section headings and blank lines are ignored, so you can leave notes');
lines.push('     between entries if you want.');
lines.push('  5. Send the whole file back and it gets applied in one pass.');
lines.push('');
lines.push('THINGS YOU WILL SEE IN THE TEXT');
lines.push('  [Client name]        a placeholder. Real content still needed.');
lines.push('  <span class="hl">…</span>   the orange highlight. Keep the tags around');
lines.push('                       whatever you want highlighted, or delete them both');
lines.push('                       to remove the emphasis.');
lines.push('  <br>                 a forced line break.');
lines.push('  <span class="q">“</span>    the orange quote marks on a testimonial title.');
lines.push('  &thinsp;             a thin space. Leave it where it is.');
lines.push('  &amp;                an ampersand.');
lines.push('');
lines.push('The hero is generated by a script rather than written in the page, so its');
lines.push('copy is in the second half of this file. It reads a little oddly out of');
lines.push('context; each stage is one position on the slider.');
lines.push('');

let n = 0;
let lastSection = null;
for (const s of htmlSlots) {
  if (s.section !== lastSection) {
    lines.push('');
    lines.push('──────────────────────────────────────────────────────────────');
    lines.push(s.section);
    lines.push('──────────────────────────────────────────────────────────────');
    lastSection = s.section;
  }
  const id = 'h' + (++n);
  map.html.push({ id, html: s.html });
  lines.push('[[' + id + ']] ' + s.html);
}

lines.push('');
lines.push('');
lines.push('══════════════════════════════════════════════════════════════');
lines.push('HERO — generated by assets/js/maturity-slider.js');
lines.push('══════════════════════════════════════════════════════════════');

let m = 0;
let lastGroup = null;
for (const s of jsSlots) {
  if (s.group !== lastGroup) {
    lines.push('');
    lines.push('── ' + s.group + ' ' + '─'.repeat(Math.max(0, 58 - s.group.length)));
    lastGroup = s.group;
  }
  const id = 'j' + (++m);
  map.js.push({ id, value: s.value, nth: s.nth });
  /* The label goes on its own line. It used to be prefixed onto the same line
     as the text, which meant the importer read "Problem: Deal knowledge..."
     as the new copy and wrote the label into the page. The round-trip test
     caught it; the rule is that nothing but the copy follows an [[id]]. */
  lines.push('    ' + s.label);
  lines.push('[[' + id + ']] ' + s.value);
}

lines.push('');
lines.push('');
lines.push('END. ' + (n + m) + ' editable strings.');
lines.push('');

fs.writeFileSync(OUT_TXT, lines.join('\n'));
fs.writeFileSync(OUT_MAP, JSON.stringify(map, null, 2));
console.log('wrote ' + path.relative(ROOT, OUT_TXT) + '  (' + n + ' from index.html, ' + m + ' from the slider)');
console.log('wrote ' + path.relative(ROOT, OUT_MAP));
